<a href="https://colab.research.google.com/github/Muhammad-Awaix/-ML-Pyhton-Projects/blob/main/Bscics_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_csv('/content/ecommerce_sales_analytics_5000.csv', parse_dates=['order_date'])
df.head(3)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   datetime64[ns]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(4), object(3)
memory usage: 468.9+ KB

In [3]:
df['payment_method'].unique()

array(['Wallet', 'Card', 'COD'], dtype=object)

In [4]:
# map function is use on a series or single columns
df['payment_type'] = df['payment_method'].map(
    {'Wallet':'Digital',
     'Card':'Digital',
     'COD':'Cash'}
)
df.sample(2)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,payment_type
1308,11309,2025-08-01,1606,Beauty,East,4,330.57,0.06,Card,10,1.7,1242.94,Digital
4083,14084,2033-03-07,1484,Electronics,North,3,490.57,0.27,Wallet,1,4.7,1074.35,Digital

In [7]:
df['payment_type'].value_counts()

payment_type
Digital    3226
Cash       1774
Name: count, dtype: int64

In [9]:
df['revenue'].describe()

count    5000.000000
mean     1021.955148
std       825.584219
min        11.210000
25%       354.527500
50%       796.650000
75%      1515.690000
max      4119.330000
Name: revenue, dtype: float64

In [13]:
#aaply is used on multipul columns and more flexibel then map
def revenue_cat(row):
    if row['revenue'] > 3500:
        return 'High'
    elif row['revenue'] >= 2000:
        return 'Medium'
    else:
        return "Low"
df['revenue_cat'] = df.apply(revenue_cat, axis=1)
df.sample(2)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,payment_type,revenue_cat
3817,13818,2032-06-14,1659,Clothing,North,6,517.62,0.19,COD,11,3.5,2515.63,Cash,Medium
1904,11905,2027-03-20,1490,Clothing,South,5,15.77,0.14,Card,4,5.0,67.81,Digital,Low

In [14]:
df['revenue_cat'].value_counts()

revenue_cat
Low       4291
Medium     683
High        26
Name: count, dtype: int64

In [15]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'product_category', 'region',
       'quantity', 'unit_price', 'discount', 'payment_method', 'delivery_days',
       'customer_rating', 'revenue', 'payment_type', 'revenue_cat'],
      dtype='object')

In [16]:
df.sample(2)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,payment_type,revenue_cat
1145,11146,2025-02-19,1182,Beauty,North,2,315.88,0.31,COD,9,4.9,435.91,Cash,Low
3847,13848,2032-07-14,1562,Clothing,North,3,485.09,0.21,Card,6,2.4,1149.66,Digital,Low

In [18]:
#pipe is used if we want to do perform some operations in sequence
def add_profit(data):
    data['profit'] = df['revenue']*0.20
    return data
def net_revinue(data):
    data['net_revinue'] = data['revenue'] - data['profit']
    return data

df = (
    df.pipe(add_profit)
    .pipe(net_revinue)
)

In [20]:
df.sample(3)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,payment_type,revenue_cat,profit,net_revinue
3496,13497,2031-07-29,1844,Home,North,2,470.52,0.26,Card,8,4.0,696.37,Digital,Low,139.274,557.096
105,10106,2022-04-16,1269,Beauty,West,6,572.68,0.25,Card,5,4.2,2577.06,Digital,Medium,515.412,2061.648
3931,13932,2032-10-06,1398,Electronics,North,7,206.72,0.02,Card,10,2.0,1418.10,Digital,Low,283.620,1134.480